### ISSUE TITLE
Vendor/autoload.php missing. Failed to open stream

### ISSUE THREAD

**Issue by Pasbiengrav** [bricebou/grav-plugin-better-typography#1]
Bonjour Brice,

Immediately after having upgraded to the latest Grav & Admin plugin versions (Grav v1.7.35 - Admin v1.10.35), on a local installation, I installed Better Typography with the `Add` button of the admin plugin.
I immediately arrived to a Crikey! :

> Whoops \ Exception \ ErrorException (E_WARNING)
require(/…/user/plugins/better-typography/vendor/autoload.php): failed to open stream: No such file or directory

There was no vendor directory inside user/plugins/better-typography.

Seems like file system/src/Grav/Common/Plugins.php ask for autoloader on line 146:

`/** @var EventDispatcher $events */
        $events = $grav['events'];
        foreach ($this->items as $instance) {
            // Register only enabled plugins.
            if ($config["plugins.{$instance->name}.enabled"] && $instance instanceof Plugin) {
                // Set plugin configuration.
                $instance->setConfig($config);
                // Register autoloader.
                if (method_exists($instance, 'autoload')) {
                    $instance->setAutoloader($instance->autoload());
                }`

then your file user/plugins/better-typography/better-typography.php at line 46:

` /**
    * Composer autoload
    *
    * @return ClassLoader
    */
    public function autoload(): ClassLoader
    {
        return require __DIR__ . '/vendor/autoload.php';
    }`

After removing your better-typography directory from my plugins directory, all went back to normal.

Just before the Crikey! error, the admin confirmed that dependencies installed well and the plugin installation was successful. I tried re-installing and same situation occurred.

I tested on a live production site (v1.7.34 - Admin v1.10.34) with similar error.

**Comment by bricebou** [comment]
Hi,

Thanks a lot for your message. Can you give it a try now, using the 0.1.1 version (https://github.com/bricebou/grav-plugin-better-typography/releases/tag/v0.1.1) ?

The vendor/ directory is now included within the repository and the error shouldn't be present anymore :)

Thanks again and sorry for the inconvenience !

**Comment by Pasbiengrav** [comment]
Tks. I re-installed manually from your link above.
The admin side of the local website works fine, but not the visitor’s side.

This file user/plugins/better-typography/better-typography.php at line 153
`        $betterTypoLanguage = array_key_exists($language, $betterTypoSettings) ? $language : 'default';
`
produces the error
`Whoops \ Exception \ ErrorException (E_WARNING)
array_key_exists(): The first argument should be either a string or an integer
`

**Comment by bricebou** [comment]
Thanks @Pasbiengrav ! I've opened a new issue for this warning : #2.
